### ISSUE TITLE
Premake5 Warnings - Deprecated Functions

### ISSUE THREAD

**Issue by xypherorion** [antopilo/Nuake#74]
Premake5 warns of two functions which will be deprecated in future versions:
dependencies\recastnavigation_p5.lua:70
premake5.lua:266

![image](https://github.com/user-attachments/assets/b4c2b191-aedc-4cad-988a-0d78f7965e99)

```
P:\Programming\Nuake>premake5 vs2022
** Warning: the flags value StaticRuntime has been deprecated and will be removed.
   Use `staticruntime "On"` instead
   @...ramming\Nuake\Nuake\dependencies\recastnavigation_p5.lua(70)

** Warning: the flags value WinMain has been deprecated and will be removed.
   Use `entrypoint "WinMainCRTStartup"` instead
   @P:\Programming\Nuake\premake5.lua(266)
```

Priority: Low

Fix Tasks:
Update dependencies\recastnavigation_p5.lua:70 to use `staticruntime "On"`
Update premake5.lua:266 to use `entrypoint "WinMainCRTStartup"`

Expected Result:
No Warnings

**Comment by antopilo** [comment]
Thank you! :)
