### ISSUE TITLE
License change to MIT

### ISSUE THREAD

**Issue by kattkieru** [antopilo/Nuake#8]
Hey there,

Would you consider a license change to MIT or BSD? Since the engine is a complete rewrite and no Quake bits are used it would be beneficial to have a more permissive license.

Thanks!

**Comment by antopilo** [comment]
Hey! For sure!

What are some things that the current license prevents you from doing? I am interest :)

Thank you

**Comment by kattkieru** [comment]
Thanks for replying and considering this!

The biggest issue is app stores.  GPL completely prohibits the ability to be on the iOS store, or on consoles.  Even if you have a binary distribution rider, most places will dismiss you outright or give you a lot of problems.

But a second big issues is that folks who work for big companies who might want to play with your engine in their spare time might not be able to, as looking at GPL code for inspiration can be problematic legally if a person even unconsciously draws inspiration from the code in another work, or does something similar in function but different in implementation.  (Seen it happen; lawyers can ruin any good party.)

Anyway, I appreciate you considering this. :)

**Comment by antopilo** [comment]
I understand, 

When it comes to publishing on IOS or consoles, would that prevent games made with the engine to be on there? 

I added the license change to the backlog, I'm going to start picking up the pace on this project as there's been some stuff taking more space in my life. 

Also, I need to start including the license of the libraries I am using as well as I do not think I'm handling licenses properly. 

If you want to help me figure out, I would appreciate it.

Thank you

**Comment by Iceman12k** [comment]
I'm definitely not a license-untangling-pro like some people are, but

Yes GPL will prevent publishing on any platform that requires their non-GPL compatbile libraries to be integrated, which includes iOS, consoles, maybe Epic Games Launcher? With Steam I have gotten around this issue in the past by making a wrapper program which talks to the game engine via an OS pipe, but it definitely isn't ideal. Even then I don't think this would pass on consoles or iOS because those platforms want direct integration with the executable afaik.

**Comment by antopilo** [comment]
Thank you, I will change the license tonight. 👍

**Comment by kattkieru** [comment]
Hey thanks for that!

Yeah re: iOS, the main issue is that it adds a layer of encryption on top of the app and limits distribution, which goes against GPL rules.  Same as consoles.  Also, if you're planning to accept pulls in the future, doing the license change now will make it clear that you intend to support broader use cases moving forwards.

Honestly, most companies won't touch GPL with a ten foot pole, and for good reason

**Comment by antopilo** [comment]
The license has been changed to MIT :)

**Comment by kattkieru** [comment]
You’re awesome!
